### ISSUE TITLE
Where can I find the code for the hex file?

### ISSUE THREAD

**Issue by HaukHuang** [LLK/scratch-link#147]
Where can I find the code for the hex file?

**Comment by apple502j** [comment]
Closed source, i.e. you can't.

**Comment by bosnivan** [comment]
Hi! Is there any chance for a hex file to become open source? It should give us more flexibility. Thanks.

**Comment by lubo-fr** [comment]
Hi! 
As some important blocks in Scratch are missing, such as IO Pin read and write, in order to implement them is there a way to get at least some specifications for the hex file ?
[Scratch micro:bit extension](https://github.com/LLK/scratch-vm/blob/develop/src/extensions/scratch3_microbit/index.js) refers to a missing project https://github.com/LLK/scratch-microbit-firmware/blob/master/protocol.md, where is it now ?
Thanks

**Comment by cwillisf** [comment]
@khanning or @ericrosenbaum, any thoughts on this discussion?
