### ISSUE TITLE
certificate problem

### ISSUE THREAD

**Issue by goddess1992** [LLK/scratch-link#169]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by goddess1992** [comment]
hello,
i have a problem with creating certificate 
this is the error i have while running "convert_certificates.sh" :

$ /cygdrive/e/projects/scratch-link-develop/Certificates/convert-certificates.sh
unable to load certificates
34359738384:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1130:
34359738384:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:290:Type=X509_CINF
34359738384:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:627:Field=cert_info, Type=X509
34359738384:error:0907400D:PEM routines:PEM_X509_INFO_read_bio:ASN1 lib:crypto/pem/pem_info.c:196:

**Comment by apple502j** [comment]
Read the docs:
> These certificates are not provided in this repository.
> Those outside the Scratch Team will need to provide their own certificates for unofficial builds.

**Comment by goddess1992** [comment]
how can i provide it ? i am a bit confused...

**Comment by goddess1992** [comment]
i think the problem is i don't have the right scartch-device-manager.key and .cer

**Comment by apple502j** [comment]
Maybe http://www.winserver.com/public/aup/HowToObtainCertificate.htm works

**Comment by goddess1992** [comment]
thanks for answering.
i'll check it

**Comment by cwillisf** [comment]
Hello!

The official Scratch certificates are not provided publicly. Those certificates would let others impersonate the Scratch team in a small way. If you want to build a custom version of Scratch Link you will need to get your own certificates for your version.

In addition to the link @apple502j shared, I would also recommend looking here: https://letsencrypt.org/getting-started/

I will close this issue since it does not appear to be a problem with Scratch Link, but you are welcome to continue the discussion.

Thanks, and good luck!
