### ISSUE TITLE
Windows scratch-link failing with `ERR_SSL_OBSOLETE_VERSION` or similar

### ISSUE THREAD

**Issue by jsyzthz** [LLK/scratch-link#179]
### Expected Behavior

connect to microbit successfully

### Actual Behavior

EDIT by @cwillisf: new problem described in https://github.com/LLK/scratch-link/issues/179#issuecomment-662346868

> projects.bundle.js:150 WebSocket connection to 'wss://device-manager.scratch.mit.edu:20110/scratch/ble' failed: Error in connection establishment: net::ERR_SSL_OBSOLETE_VERSION

~~WebSocket connection to 'wss://device-manager.scratch.mit.edu:20110/scratch/ble' failed: Error in connection establishment: net::ERR_CERT_REVOKED
value @ projects.bundle.js:150~~

### Steps to Reproduce

1. open https://scratch.mit.edu/
2. login with own account
3. launch scratch-link tool
4. add microbit extension
5. connect to microbit
6. got error

### Operating System and Browser

Chrome  84.0.4147.89 /Window 10

**Comment by jsyzthz** [comment]
my scratch link version is 1.1.46.0

**Comment by apple502j** [comment]
@jsyzthz Please update Scratch Link.

**Comment by jsyzthz** [comment]
@apple502j 
i download&install the release version（1.3.57.0） from official(msi package)，now i got another error:

`projects.bundle.js:150 WebSocket connection to 'wss://device-manager.scratch.mit.edu:20110/scratch/ble' failed: Error in connection establishment: net::ERR_SSL_OBSOLETE_VERSION`

it seems the wss certificate has some problem with Chrome broswer.

**Comment by YanMinge** [comment]
I also have this issue. 
 https://github.com/LLK/scratch-vm/issues/2524

**Comment by cwillisf** [comment]
This seems to affect Chrome-family browsers as well as Firefox.

**Comment by BWMerlin** [comment]
Here is what I have tried.

Laptop 1 - working
Windows 10 1809 build 17763.1217/17763.1282
Scratch link 1.3.57.0
Firefox 66.0.5/69.0/72.0.2 (Firefox 78.0.2 NOT working)
Edge 44.17763.831.0 HTML 18.17763
Chrome 84.0.4147.89/84.0.4147.105

Laptop 2 - NOT working
Windows 10 1909 build 18363.959
Scratch link 1.3.57.0
Firefox 78.0.2
Edge 84.0.522.44
Chrome 84.0.4147.105

Laptop 3 - Working
Windows 10 1909 build 18363.959
Scratch link 1.3.57.0
Edge 44.17763.831.0 HTML 18.17763
Chrome 84.0.4147.105 NOT working

It would appear that the issue is related to a Windows update and certain browser versions will not work if they are updated (Firefox 78.0.2 for example) while Edge 44.17763.831.0 HTML 18.17763 will happily work on the same updated version of Windows
